name: 吾爱破解签到
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  0 10 * * *
  workflow_dispatch:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: 安装环境
      run:
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 签到
      run: |
        python3 ./scripts/pojie.py
      env:
        PJ_COOKIE: ${{ secrets.PJ_COOKIE }}
