name: 喜马拉雅极速版

on:
  schedule:
    - cron: '*/30 * * * * '
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt 
        
      - name: 'run 喜马拉雅极速版' 
        run: python3 ./scripts/xmly_speed.py 
        env:
            XMLY_SPEED_COOKIE: ${{ secrets.XMLY_SPEED_COOKIE }}  #必须
            QYWX_CORPID: ${{ secrets.QYWX_CORPID }}
            QYWX_CORPSECRET: ${{ secrets.QYWX_CORPSECRET }}
            QYWX_AGENTID: ${{ secrets.QYWX_AGENTID }}            
          